import { useState, useCallback } from "react";
import { AppLayout } from "@/components/AppLayout";
import { Upload, Mic, Search, Download, FileAudio, FileText, Loader2, Sparkles } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { mockTranscript, mockAudits, scoreLabels, type QualityScore } from "@/lib/mock-data";

const AUDIO_API   = import.meta.env.VITE_AUDIO_API   ?? "http://127.0.0.1:8000";
const CHAT_API    = import.meta.env.VITE_CHAT_API    ?? "http://127.0.0.1:8001";
const QUALITY_API = import.meta.env.VITE_QUALITY_API ?? "http://127.0.0.1:8002";   // ← NEW: quality scoring server

const AUDIO_EXTENSIONS = ["m4a", "mp3", "wav", "ogg", "flac", "aac", "webm"];
const TEXT_EXTENSIONS  = ["txt", "csv", "json"];

type TranscriptEntry = {
  speaker: string;
  text: string;
  start?: number;
};

// Shape of what port 8002 returns
export type QualityScores = {
  empathy: number;
  compliance: number;
  resolution: number;
  efficiency_score?: number;
  avg_response_time?: number;
  empathy_timeline?: { stage: string; score: number }[];
  compliance_steps?: { step: string; score: number }[];
  resolution_progress?: { stage: string; score: number }[];
  reasoning?: string;
};

// ── localStorage key shared with Reports page ────────────────────────────────
export const QUALITY_SCORES_KEY = "auraq_quality_scores";

const selected = mockAudits[0];

const generateReport = (transcript: TranscriptEntry[], summary: string) => {
  const scores = selected.scores;
  const lines: string[] = [];

  lines.push("=".repeat(60));
  lines.push("          AURAQ — AI QUALITY AUDIT REPORT");
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(`Call Title:    ${selected.title}`);
  lines.push(`Agent:         ${selected.agent}`);
  lines.push(`Date:          ${selected.date}`);
  lines.push(`Duration:      ${selected.duration}`);
  lines.push(`Overall Score: ${selected.overallScore}/100`);
  lines.push(`Status:        ${selected.status}`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("  QUALITY SCORES");
  lines.push("-".repeat(60));
  (Object.keys(scores) as (keyof QualityScore)[]).forEach((key) => {
    lines.push(`  ${scoreLabels[key].padEnd(25)} ${scores[key]}/100`);
  });
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("  AI AUDITOR SUMMARY");
  lines.push("-".repeat(60));
  lines.push("");
  lines.push(`  ${summary || selected.summary}`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("  FULL TRANSCRIPT");
  lines.push("-".repeat(60));
  lines.push("");
  const displayTranscript = transcript.length > 0
    ? transcript
    : mockTranscript.map(e => ({ speaker: e.speaker === "agent" ? "Speaker 00" : "Speaker 01", text: e.text, start: undefined }));
  displayTranscript.forEach((entry) => {
    const label = entry.speaker === "Speaker 00" ? "AGENT" : "CUSTOMER";
    const time  = entry.start != null ? `${entry.start.toFixed(1)}s` : "";
    lines.push(`  [${time}] ${label}:`);
    lines.push(`  ${entry.text}`);
    lines.push("");
  });
  lines.push("=".repeat(60));
  lines.push("  Report generated by AuraQ AI Auditor");
  lines.push(`  Generated on: ${new Date().toLocaleString()}`);
  lines.push("=".repeat(60));

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `AuraQ_Report_${selected.id}_${selected.date}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

function getFileType(file: File): "audio" | "text" | "unknown" {
  const ext = file.name.split(".").pop()?.toLowerCase() ?? "";
  if (AUDIO_EXTENSIONS.includes(ext)) return "audio";
  if (TEXT_EXTENSIONS.includes(ext))  return "text";
  return "unknown";
}

function formatTime(seconds?: number): string {
  if (seconds == null) return "";
  const m = Math.floor(seconds / 60).toString().padStart(2, "0");
  const s = Math.floor(seconds % 60).toString().padStart(2, "0");
  return `${m}:${s}`;
}

// ─── component ───────────────────────────────────────────────────────────────

const Dashboard = () => {
  const [dragOver,         setDragOver]         = useState(false);
  const [files,            setFiles]            = useState<File[]>([]);
  const [uploading,        setUploading]        = useState(false);
  const [uploadStatus,     setUploadStatus]     = useState<string>("");
  const [transcript,       setTranscript]       = useState<TranscriptEntry[]>([]);
  const [summary,          setSummary]          = useState<string>("");
  const [searchTranscript, setSearchTranscript] = useState("");
  const [lastFileType,     setLastFileType]     = useState<"audio" | "text" | "">("");
  const [qualityStatus,    setQualityStatus]    = useState<string>("");  // NEW

  // ── upload handler ────────────────────────────────────────────────────────

  const uploadFile = useCallback(async (file: File) => {
    const type = getFileType(file);
    if (type === "unknown") {
      setUploadStatus(`⚠️ Unsupported file type: ${file.name}`);
      return;
    }

    setUploading(true);
    setUploadStatus(`Uploading ${file.name}…`);
    setQualityStatus("⏳ Waiting for quality analysis…");
    setLastFileType(type);

    try {
      // ── STEP 1: Send to transcription server (8000 or 8001) ──────────────
      const formData1 = new FormData();
      formData1.append("file", file);
      const endpoint = type === "audio"
        ? `${AUDIO_API}/upload`
        : `${CHAT_API}/upload-text`;

      const res  = await fetch(endpoint, { method: "POST", body: formData1 });
      if (!res.ok) throw new Error(`Transcription server error: ${res.status}`);
      const data = await res.json();

      setSummary(data.summary ?? "");
      setUploadStatus(`✅ ${file.name} processed successfully`);

      // Fetch transcript after upload
      await fetchTranscript(type);

      // ── STEP 2: ALSO send to quality scoring server (8002) ───────────────
      setQualityStatus("🔍 Analyzing quality scores…");
      const formData2 = new FormData();
      formData2.append("file", file);

      const qualityRes = await fetch(`${QUALITY_API}/analyze-quality`, {
        method: "POST",
        body: formData2,
      });

      if (!qualityRes.ok) throw new Error(`Quality server error: ${qualityRes.status}`);
      const qualityData: QualityScores = await qualityRes.json();

      // Persist to localStorage so Reports page can read it
      localStorage.setItem(QUALITY_SCORES_KEY, JSON.stringify(qualityData));
      setQualityStatus("✅ Quality scores updated — check Reports page");

    } catch (err: any) {
      setUploadStatus(`❌ Error: ${err.message}`);
      setQualityStatus("");
    } finally {
      setUploading(false);
    }
  }, []);

  // ── transcript fetcher ────────────────────────────────────────────────────

  const fetchTranscript = async (type: "audio" | "text") => {
    try {
      const url = type === "audio"
        ? `${AUDIO_API}/get-transcript`
        : `${CHAT_API}/get-text-transcript`;
      const res  = await fetch(url);
      if (!res.ok) return;
      const data: TranscriptEntry[] = await res.json();
      setTranscript(data ?? []);
    } catch {
      // silently ignore — backend may not be running
    }
  };

  // ── drag & drop ───────────────────────────────────────────────────────────

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const dropped = Array.from(e.dataTransfer.files);
    if (dropped.length > 0) {
      setFiles((prev) => [...prev, ...dropped]);
      uploadFile(dropped[0]);
    }
  }, [uploadFile]);

  const handleBrowse = () => {
    const input    = document.createElement("input");
    input.type     = "file";
    input.accept   = "audio/*,.txt,.json,.csv";
    input.multiple = false;
    input.onchange = () => {
      if (input.files && input.files[0]) {
        setFiles((prev) => [...prev, input.files![0]]);
        uploadFile(input.files![0]);
      }
    };
    input.click();
  };

  // ── derived data ──────────────────────────────────────────────────────────

  const displayTranscript: TranscriptEntry[] =
    transcript.length > 0
      ? transcript
      : mockTranscript.map((e) => ({
          speaker: e.speaker === "agent" ? "Speaker 00" : "Speaker 01",
          text:    e.text,
          start:   undefined,
        }));

  const filteredTranscript = displayTranscript.filter((entry) =>
    entry.text.toLowerCase().includes(searchTranscript.toLowerCase())
  );

  // ─── render ───────────────────────────────────────────────────────────────

  return (
    <AppLayout>
      <div className="max-w-[1200px] mx-auto space-y-6">

        {/* Page Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-heading font-bold tracking-tight">Home Page</h1>
            <p className="text-muted-foreground mt-1 text-sm">Upload, transcribe and analyze customer calls</p>
          </div>
          <Button
            onClick={() => generateReport(displayTranscript, summary)}
            className="rounded-xl bg-gradient-to-r from-primary to-chart-4 text-white hover:opacity-90 glow-primary"
          >
            <Download className="h-4 w-4 mr-2" /> Download Report
          </Button>
        </div>

        {/* Stats Row */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="glass-card card-hover rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="h-2 w-2 rounded-full bg-primary animate-pulse-glow" />
              <span className="text-[11px] uppercase tracking-widest text-muted-foreground font-semibold">Total Files</span>
            </div>
            <div className="text-4xl font-heading font-black">{files.length > 0 ? files.length : 4}</div>
            <p className="text-xs text-muted-foreground mt-1">uploaded</p>
          </div>
          <div className="glass-card card-hover rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="h-2 w-2 rounded-full bg-success" />
              <span className="text-[11px] uppercase tracking-widest text-muted-foreground font-semibold">Avg Satisfaction</span>
            </div>
            <div className="text-4xl font-heading font-black">—</div>
            <p className="text-xs text-muted-foreground mt-1">last {files.length > 0 ? files.length : 4} files</p>
          </div>
          <div className="glass-card card-hover rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="h-2 w-2 rounded-full bg-chart-4" />
              <span className="text-[11px] uppercase tracking-widest text-muted-foreground font-semibold">Avg Emotion</span>
            </div>
            <div className="text-4xl font-heading font-black">—</div>
            <p className="text-xs text-muted-foreground mt-1">no data yet</p>
          </div>
        </div>

        {/* Upload Area */}
        <div
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
          onClick={!uploading ? handleBrowse : undefined}
          className={`glass-card rounded-2xl p-12 md:p-16 text-center transition-all border-2 border-dashed ${
            uploading
              ? "border-primary/60 bg-primary/5 cursor-wait"
              : dragOver
              ? "border-primary bg-primary/5 glow-primary cursor-copy"
              : "border-border/30 hover:border-primary/40 cursor-pointer"
          }`}
        >
          <div className="flex flex-col items-center gap-4">
            {uploading ? (
              <>
                <div className="h-16 w-16 rounded-2xl bg-primary/20 flex items-center justify-center">
                  <Loader2 className="h-7 w-7 text-primary animate-spin" />
                </div>
                <h3 className="text-xl font-heading font-bold">Processing…</h3>
                <p className="text-sm text-muted-foreground">{uploadStatus}</p>
                {qualityStatus && (
                  <p className="text-xs text-muted-foreground">{qualityStatus}</p>
                )}
              </>
            ) : (
              <>
                <div className="h-16 w-16 rounded-2xl bg-primary flex items-center justify-center glow-primary animate-glow-pulse">
                  <Upload className="h-7 w-7 text-primary-foreground" />
                </div>
                <h3 className="text-xl font-heading font-bold">Upload Your Call</h3>

                {/* File type pills — now shows all 3 servers */}
                <div className="flex items-center gap-3 mt-1 flex-wrap justify-center">
                  <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                    <FileAudio className="h-3 w-3" /> Audio → :8000
                  </span>
                  <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                    <FileText className="h-3 w-3" /> Text → :8001
                  </span>
                  <span className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-3 py-1">
                    <Sparkles className="h-3 w-3" /> Quality → :8002
                  </span>
                </div>

                <p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground font-medium">
                  Drag and drop or click to browse • .M4A .MP3 .WAV .TXT .CSV
                </p>

                {uploadStatus && (
                  <p className="text-xs mt-1 text-muted-foreground">{uploadStatus}</p>
                )}
                {qualityStatus && (
                  <p className="text-xs text-muted-foreground">{qualityStatus}</p>
                )}
              </>
            )}
          </div>
        </div>

        {/* AI Summary */}
        <div className="rounded-2xl overflow-hidden bg-gradient-to-br from-primary/10 via-chart-4/5 to-transparent border border-primary/20">
          <div className="px-6 pt-5 pb-4 flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <h3 className="text-xs font-heading font-bold uppercase tracking-[0.15em] text-primary">
              Summary
            </h3>
            {lastFileType && (
              <span className="ml-auto text-[10px] uppercase tracking-widest text-muted-foreground bg-muted/50 rounded-full px-2 py-0.5">
                {lastFileType === "audio" ? "Audio Call" : "Text Chat"}
              </span>
            )}
          </div>
          <div className="px-6 pb-6">
            {summary ? (
              <p className="text-sm leading-relaxed text-foreground/80">{summary}</p>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                Upload a call or chat file to generate an AI summary…
              </p>
            )}
          </div>
        </div>

        {/* Live Transcript */}
        <div className="rounded-2xl overflow-hidden bg-[hsl(210_20%_95%)] text-[hsl(222_47%_11%)]">
          <div className="px-6 pt-6 pb-4 flex items-center gap-2">
            <Mic className="h-4 w-4 text-primary" />
            <h3 className="text-xs font-heading font-bold uppercase tracking-[0.15em] text-primary">
              {transcript.length > 0 ? "Transcript" : "Live Transcript (demo)"}
            </h3>
            {transcript.length > 0 && (
              <span className="ml-auto text-[10px] text-muted-foreground">{transcript.length} turns</span>
            )}
          </div>
          <div className="px-6 pb-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search transcript…"
                value={searchTranscript}
                onChange={(e) => setSearchTranscript(e.target.value)}
                className="pl-10 bg-white border-[hsl(220_13%_85%)] rounded-xl text-[hsl(222_47%_11%)]"
              />
            </div>
          </div>
          <ScrollArea className="h-[420px]">
            <div className="px-6 pb-6 space-y-6">
              {filteredTranscript.length === 0 && (
                <p className="text-sm text-muted-foreground text-center py-8">No results found.</p>
              )}
              {filteredTranscript.map((entry, i) => {
                const isAgent = entry.speaker === "Speaker 00";
                return (
                  <div key={i} className={`flex flex-col ${!isAgent ? "items-end" : "items-start"}`}>
                    <div className="flex items-center gap-2 mb-1.5">
                      {isAgent ? (
                        <>
                          <span className="text-[11px] font-bold uppercase tracking-wider text-primary">Agent</span>
                          {entry.start != null && (
                            <span className="text-[11px] text-[hsl(220_13%_55%)]">{formatTime(entry.start)}</span>
                          )}
                        </>
                      ) : (
                        <>
                          {entry.start != null && (
                            <span className="text-[11px] text-[hsl(220_13%_55%)]">{formatTime(entry.start)}</span>
                          )}
                          <span className="text-[11px] font-bold uppercase tracking-wider text-chart-4">Customer</span>
                        </>
                      )}
                    </div>
                    <div
                      className={`max-w-[80%] rounded-2xl px-5 py-3 text-sm leading-relaxed ${
                        isAgent
                          ? "bg-[hsl(210_20%_88%)] text-[hsl(222_47%_11%)] rounded-tl-md"
                          : "bg-gradient-to-r from-primary to-primary/80 text-white rounded-tr-md"
                      }`}
                    >
                      {entry.text}
                    </div>
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        </div>

      </div>
    </AppLayout>
  );
};

export default Dashboard;
